apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: istio-ingressgateway

resources:
  - ingress-gateway.yaml
  - secret-reader.yaml
  - gateway-service.yaml
  - hpa.yaml
  - pdb.yaml
  - namespace.yaml